### PR TITLE
Ac

### PR DESCRIPTION
**Pull request by arpcorrea**
Hello Ilyass, how are you? I hope everything is alright.

I just added some modifications to include the degree of intimate contact. Previous code was not severely changed, just slight modifications were done in order to run the new module

### CODE REVIEW

**Review by ilyasst — CHANGES_REQUESTED** [review]
Could you please review your code structure ?
I believe that the folder `./consolidate` should be removed altogether and replaced by `./Consolidation OOP/consolidate`.  
Thanks.

**Comment by ilyasst** [comment]
Also please take a look at this error I get:
```
(.env) buster@buster-VM:~/temp/consolidation-works/Consolidation OOP$ python main.py 
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    model_IC = IntimateContact()
TypeError: __init__() missing 2 required positional arguments: 'meshes' and 'deck'
```

**Review by ilyasst — CHANGES_REQUESTED** [review]
```
(.env) buster@buster-VM:~/temp/consolidation-works/Consolidation OOP$ python main.py 
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    model_IC = IntimateContact()
TypeError: __init__() missing 2 required positional arguments: 'meshes' and 'deck'

```

**Comment by arpcorrea** [comment]
Hey Ilyass,
Everything was deleted from ./Consolidation OOP/consolidate and replaced to ./consolidate
The error is already solved

**Review by ilyasst — APPROVED** [review]
Code works, file/folder structure looks good. Approved :heavy_check_mark: 
Thank you for the PR.

**Comment by ilyasst** [comment]
@EthanCabon Could you try to run the code from this PR on your machine (https://gist.github.com/adam-p/15413fabef6cffecd897) ?
Last step before finalizing the merge will be your check, please let us know if the code from this PR runs for you, I'll merge/close this PR after that. Please add your review when you can.

**Pull request merged**
